// branching - гілкування

// Оператор - if

// if (// тут запис. вираз - який прирівнюється до буля) {}
// тут тіло , вираз якого виконається якщо він однаковий з булем в круглих дужках
// }

// або по іншому., якщо (да або тру) виконуй тіло

// if (15 > 30) { // не виконається
//     console.log('x > y');
// }

// if (35 > 30) { //  виконається
//     console.log('x > y');
// }


//    оператор if else

// if (5 > 30) {
//     console.log('x > y');
// } else {
//     console.log('x < y');
// }


//   Задача 1
// Залежно від рівня зарплати вивести повідомлення

const salary = 800;

// if (salary < 500) {
//     console.log('Рівень1');
// } else if (salary > 500 && salary < 1500) {
//     console.log('Рівень2');
// } else {
//     console.log('Рівень4') // якщо більше 1500 тоді треба додавати вкінці else як тут
// }



//          тернарний оператор - використ тоді коли треба змінити значення в змінній


// const balanse = 1000;
// let massage;

// if (balanse >= 0) {
//     massage = 'Positiv balanse';
// } else {
//     massage = 'Negative balanse'
// }

// console.log(massage);

//   цей вираз можна замінити.


// const massage = balanse >= 0 ? 'Positiv balanse' : 'negativ balanse';

// console.log(massage);
